// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lshjvntdqtldhcggzddi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzaGp2bnRkcXRsZGhjZ2d6ZGRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzY2MzEsImV4cCI6MjA2MzMxMjYzMX0.A16StpndRjL8GDpZ4D2BwcApde6GnkohNBkwGFeqS3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);